'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var START_PROJECT_DATABASE_CHANGE = exports.START_PROJECT_DATABASE_CHANGE = 'START_PROJECT_DATABASE_CHANGE';
var END_PROJECT_DATABASE_CHANGE = exports.END_PROJECT_DATABASE_CHANGE = 'END_PROJECT_DATABASE_CHANGE';
var CHANGE_FOCUSED_TASKLIST = exports.CHANGE_FOCUSED_TASKLIST = "CHANGE_FOCUSED_TASKLIST";
var SELECT_TASK = exports.SELECT_TASK = "SELECT_TASK";
var OPEN_TASK = exports.OPEN_TASK = "OPEN_TASK";
var CLOSE_TASK = exports.CLOSE_TASK = 'CLOSE_TASK';
var START_TASK_MOVE = exports.START_TASK_MOVE = "START_TASK_MOVE";
var START_TASK_MOVE_IN_DATABASE = exports.START_TASK_MOVE_IN_DATABASE = 'START_TASK_MOVE_IN_DATABASE';
var END_TASK_MOVE = exports.END_TASK_MOVE = "END_TASK_MOVE";
var GET_PROJECTS = exports.GET_PROJECTS = "GET_PROJECTS";
var START_PROJECTS_FETCH = exports.START_PROJECTS_FETCH = 'START_PROJECTS_FETCH';
var RECEIVE_PROJECTS = exports.RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
var START_TASKS_FETCH = exports.START_TASKS_FETCH = 'START_TASKS_FETCH';
var RECEIVE_TASKS = exports.RECEIVE_TASKS = 'RECEIVE_TASKS';
var START_TASKLISTS_FETCH = exports.START_TASKLISTS_FETCH = 'START_TASKLISTS_FETCH';
var LOCK_APP = exports.LOCK_APP = 'LOCK_APP';
var UNLOCK_APP = exports.UNLOCK_APP = 'UNLOCK_APP';
var SET_LAST_BACKUP_MESSAGE = exports.SET_LAST_BACKUP_MESSAGE = 'SET_LAST_BACKUP_MESSAGE';
var SET_OPEN_TASKLIST_SETTINGS_MENU_ID = exports.SET_OPEN_TASKLIST_SETTINGS_MENU_ID = 'SET_OPEN_TASKLIST_SETTINGS_MENU_ID';
var OPEN_CALENDAR = exports.OPEN_CALENDAR = 'OPEN_CALENDAR';
var CLOSE_CALENDAR = exports.CLOSE_CALENDAR = 'CLOSE_CALENDAR';
var START_TASKLIST_ADD = exports.START_TASKLIST_ADD = 'START_TASKLIST_ADD';
var START_TASK_ADD = exports.START_TASK_ADD = 'START_TASK_ADD';
var CHANGE_TASKLIST_WIDGET_HEADER = exports.CHANGE_TASKLIST_WIDGET_HEADER = 'CHANGE_TASKLIST_WIDGET_HEADER';
var RECEIVE_TASKLISTS = exports.RECEIVE_TASKLISTS = 'RECEIVE_TASKLISTS';
var START_PROJECTLAYOUTS_FETCH = exports.START_PROJECTLAYOUTS_FETCH = 'START_PROJECTLAYOUTS_FETCH';
var RECEIVE_PROJECTLAYOUT = exports.RECEIVE_PROJECTLAYOUT = 'RECEIVE_PROJECTLAYOUT';
var SELECT_PROJECT = exports.SELECT_PROJECT = 'SELECT_PROJECT';
var SET_PROJECTS_HAVE_PENDING_WRITES = exports.SET_PROJECTS_HAVE_PENDING_WRITES = 'SET_PROJECTS_HAVE_PENDING_WRITES';
var SET_PROJECTLAYOUTS_HAVE_PENDING_WRITES = exports.SET_PROJECTLAYOUTS_HAVE_PENDING_WRITES = 'SET_PROJECTLAYOUTS_HAVE_PENDING_WRITES';
var SET_TASKLISTS_HAVE_PENDING_WRITES = exports.SET_TASKLISTS_HAVE_PENDING_WRITES = 'SET_TASKLISTS_HAVE_PENDING_WRITES';
var SET_TASKS_HAVE_PENDING_WRITES = exports.SET_TASKS_HAVE_PENDING_WRITES = 'SET_TASKS_HAVE_PENDING_WRITES';
